"use server";

// Server actions for the account-page email preferences section. There
// are two:
//
//   loadEmailPrefs   — read-only fetch for the section's initial render.
//                      Lives here so the page component can be a server
//                      component without manually constructing a SB
//                      client.
//   setEmailPrefs    — toggle weekly_digest_opted_in. Upserts the row
//                      so first-time toggles work without a separate
//                      "create row" step.
//
// Both use the request-scoped Supabase client (RLS-enforced — the
// policies allow each user to read/write only their own row).

import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/auth/session";
import { createServerClient } from "@/lib/supabase/server";

export type EmailPrefs = {
  weeklyDigestOptedIn: boolean;
  lastDigestSentAt: string | null;
};

export async function loadEmailPrefs(): Promise<EmailPrefs> {
  const session = await requireSession();
  const sb = await createServerClient();
  const { data } = await sb
    .from("email_preferences")
    .select("weekly_digest_opted_in, last_digest_sent_at")
    .eq("user_id", session.userId)
    .maybeSingle();
  return {
    weeklyDigestOptedIn: Boolean(data?.weekly_digest_opted_in),
    lastDigestSentAt: (data?.last_digest_sent_at as string | null) ?? null,
  };
}

export type EmailPrefsFormState = {
  error?: string;
  info?: string;
};

// Toggle target comes in via the `opt_in` field. We read whatever the
// hidden input sent rather than flipping in JS — that keeps the action
// resilient to the user double-clicking ("opt me in twice" still results
// in opted-in=true, no toggle race).
export async function setEmailPrefsAction(
  _prev: EmailPrefsFormState,
  form: FormData,
): Promise<EmailPrefsFormState> {
  const session = await requireSession();
  const want = form.get("opt_in") === "true";

  const sb = await createServerClient();
  // Upsert so the first toggle creates the row. The unsubscribe_token
  // default is generated by the table (gen_random_uuid()) — we don't
  // touch it on update, so existing tokens stay stable across opt-in/out
  // cycles.
  const { error } = await sb.from("email_preferences").upsert(
    {
      user_id: session.userId,
      weekly_digest_opted_in: want,
      // Don't reset last_digest_sent_at — preserve cron idempotency
      // even if the user toggles off then back on within the week.
    },
    { onConflict: "user_id" },
  );
  if (error) {
    return { error: error.message };
  }

  revalidatePath("/account");
  return {
    info: want
      ? "You're opted in. The next digest goes out Friday."
      : "You're opted out. We won't send any more weekly digests.",
  };
}
